# Generated by Django 4.2 on 2023-04-04 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_scope_arcticle_id_alter_scope_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='arcticle_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article'),
        ),
    ]
