# Generated by Django 4.2 on 2023-04-04 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_scope_arcticle_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope',
            old_name='tag_id',
            new_name='tag',
        ),
        migrations.AlterField(
            model_name='scope',
            name='arcticle_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope', to='articles.article'),
        ),
    ]
